name: PHP Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  psalm:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Cache vendor directory
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Check composer.lock
        run: composer validate --no-check-all --no-check-publish

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Psalm
        run: vendor/bin/psalm --output-format=github --long-progress --no-diff

      - name: PHPUnit
        run: vendor/bin/phpunit tests --printer mheap\\GithubActionsReporter\\Printer --coverage-clover clover.xml -vvv

      - name: Monitor coverage
        if: ${{ github.event_name == 'pull_request' }}
        uses: slavcodev/coverage-monitor-action@1.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "clover.xml"
          threshold_alert: 10
          threshold_warning: 50
          comment_mode: update