name: Tests

on:
    push:
    pull_request:
        branches: [ 1.x ]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    phpunit:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ '8.1', '8.2', '8.3' ]
                symfony: [ '5.4', '6.4', '7.0', '7.1' ]
                dependencies: [ 'highest', 'lowest' ]
                exclude:
                    -   php: '8.1'
                        symfony: '7.0'
                    -   php: '8.1'
                        symfony: '7.1'
        services:
            postgres:
                image: postgres:16
                env:
                    POSTGRES_DB: purgatory
                    POSTGRES_PASSWORD: password
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 3
        env:
            SYMFONY_REQUIRE: ${{ matrix.symfony }}.*
        name: PHP ${{ matrix.php }} & Symfony ${{ matrix.symfony }}${{ matrix.dependencies == 'lowest' && ' (lowest)' || '' }} Test
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    ini-values: zend.exception_ignore_args=false
                    tools: flex

            -   name: Install Dependencies
                uses: ramsey/composer-install@v2
                with:
                    composer-options: '--prefer-dist'
                    dependency-versions: ${{ matrix.dependencies }}

            -   name: Run Tests
                env:
                    DATABASE_URL: 'postgresql://postgres:password@127.0.0.1:5432/purgatory?serverVersion=16'
                run: vendor/bin/phpunit --log-junit=junit.xml --coverage-text --coverage-clover=coverage.xml

            -   name: Publish Test Report
                uses: mikepenz/action-junit-report@v4
                if: always()
                with:
                    check_name: PHPUnit Execution Report
                    fail_on_failure: 'true'
                    require_tests: 'true'
                    report_paths: ./junit.xml

            -   name: Upload Test Coverage
                if: ${{ success() }}
                uses: codecov/codecov-action@v4
                with:
                    codecov_yml_path: .github/codecov.yaml
                    fail_ci_if_error: true
                    file: coverage.xml
                    flags: ${{ matrix.php }}
                    token: ${{ secrets.CODECOV_TOKEN }}
